#!/bin/sh -e
sv start dbus >/dev/null
# Wait for dbus to be fully ready
timeout=10
while [ $timeout -gt 0 ]; do
    dbus-send --system --dest=org.freedesktop.DBus \
        --type=method_call --print-reply \
        /org/freedesktop/DBus org.freedesktop.DBus.ListNames \
        >/dev/null 2>&1 && break
    sleep 1
    timeout=$((timeout - 1))
done
# Kill any D-Bus-activated elogind instance
if [ -f /run/elogind.pid ]; then
    kill "$(cat /run/elogind.pid)" 2>/dev/null
    sleep 1
    rm -f /run/elogind.pid
fi
exec /usr/lib/elogind/elogind 2>/dev/null
