cmap ;cac $HOME/.cache
cmap ;cf $HOME/.config
cmap ;D $HOME/Downloads
cmap ;d $HOME/Documents
cmap ;dt $HOME/.local/share
cmap ;rr $HOME/.local/src
cmap ;h $HOME
cmap ;m $HOME/Music
cmap ;mn /mnt
cmap ;pp $HOME/Pictures
cmap ;sc $HOME/.local/bin
cmap ;src $HOME/.local/src
cmap ;vv $HOME/Videos
cmap ;co $HOME/code
cmap ;proj $HOME/code/PROJECTS
cmap ;sites $HOME/code/PROJECTS/VULTR_0/sites
cmap ;timbeach $HOME/code/PROJECTS/VULTR_0/sites/timbeach.com
cmap ;zenshinsuru $HOME/code/PROJECTS/VULTR_0/sites/zenshinsuru.com
cmap ;omostholy $HOME/code/PROJECTS/VULTR_0/sites/omostholytheotokos.com
cmap ;posixparty $HOME/code/PROJECTS/VULTR_0/sites/posixparty.com
cmap ;crypto $HOME/code/PROJECTS/VULTR_0/sites/cryptographyisbeautiful.com
cmap ;wovenaudio $HOME/code/PROJECTS/VULTR_0/sites/wovenaudio.com
cmap ;thequantitative $HOME/code/PROJECTS/VULTR_0/sites/thequantitative.com
cmap ;ellbeach $HOME/code/PROJECTS/VULTR_0/sites/ellbeach.com
cmap ;ezrabeach $HOME/code/PROJECTS/VULTR_0/sites/ezrabeach.com
cmap ;ionosphere $HOME/code/PROJECTS/ionosphere
cmap ;aegix $HOME/code/PROJECTS/AEGIX/
cmap ;gohan $HOME/code/PROJECTS/AEGIX/gohan
cmap ;barbs $HOME/code/PROJECTS/AEGIX/barbs
cmap ;dwm $HOME/code/PROJECTS/AEGIX/dwm
cmap ;dwmblocks $HOME/code/PROJECTS/AEGIX/dwmblocks
cmap ;website $HOME/code/PROJECTS/AEGIX/website
cmap ;sql $HOME/code/STRIDE/3_SQL
cmap ;stride $HOME/code/STRIDE/
cmap ;tad $HOME/code/STRIDE/1_APPS/TAD
cmap ;ng $HOME/code/STRIDE/1_APPS/NG
cmap ;sims $HOME/code/STRIDE/1_APPS/SIMS
cmap ;gary $HOME/code/STRIDE/1_APPS/GARY
cmap ;aireading $HOME/code/STRIDE/1_APPS/AI_READING
cmap ;obss $HOME/Videos/obs
cmap ;docs $HOME/Documents/PERSONAL
cmap ;house $HOME/Documents/PERSONAL/HOME_BUYING/421_Northcott
cmap ;mh $HOME/Audio/MENTAL_HEALTH
cmap ;lhfam $HOME/code/PROJECTS/LHFAM
cmap ;pps $HOME/Pictures/Screenshots
cmap ;colony $HOME/code/PROJECTS/VULTR_0/sites/colonyinvestmentsllc.com
cmap ;radios $HOME/code/PROJECTS/RADIOS
cmap ;stride $HOME/code/STRIDE
cmap ;storystudio $HOME/code/STRIDE/1_APPS/ST_ST_TIMOTHY
cmap ;bf $HOME/.config/shell/bm-files
cmap ;bd $HOME/.config/shell/bm-dirs
cmap ;cfx $HOME/.config/x11/xresources
cmap ;cfb ~/.local/src/dwmblocks/config.h
cmap ;cfv $HOME/.config/nvim/init.vim
cmap ;cfz $HOME/.config/zsh/.zshrc
cmap ;cfa $HOME/.config/shell/aliasrc
cmap ;cfp $HOME/.config/shell/profile
cmap ;cfm $HOME/.config/mutt/muttrc
cmap ;cfn $HOME/.config/newsboat/config
cmap ;cfu $HOME/.config/newsboat/urls
cmap ;cfmb $HOME/.config/ncmpcpp/bindings
cmap ;cfmc $HOME/.config/ncmpcpp/config
cmap ;cfl $HOME/.config/lf/lfrc
cmap ;cfL $HOME/.config/lf/scope
cmap ;cfX $HOME/.config/sxiv/exec/key-handler
